### ISSUE TITLE
Il caricamento xml fallisce su edge

### ISSUE THREAD

**Issue by emilianominella** [massivex/fattura-elettronica-angular#1]
Un utente ci segnala che l'applicazione di esempio non carica gli xml quando gira sul browser edge invece su chrome funziona correttamente.

**Comment by savarex** [comment]
Grazie!
Il problema è stato risolto in questo commit
https://github.com/massivex/fattura-elettronica-angular/commit/d70812503b85deae8cca2d77913f0f7ede254cfe

Sarà pubblicato nella prossima versione
